BookStore/Models/Order.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Email { get; set; }

        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }
}

BookStore/Controllers/BookController.cs
using BookStore.Data;
using BookStore.Data.Services;
using BookStore.Data.Staic;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Authorize]

    public class BookController : Controller
    {
        private readonly IBookService _services;

        public BookController(IBookService service)
        {
            _services = service;
        }


        public async Task<IActionResult> Index(string searchString)
        {
            var allBooks = await _services.GetAllAsync(n => n.Author, n => n.Category);

            if (!string.IsNullOrEmpty(searchString))
            {
               
                allBooks = allBooks.Where(book => book.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            return View(allBooks);
        }


        public async Task<IActionResult> Details(int id)
        {
            var bookDetail = await _services.GetBookByIdAsync(id);
            return View(bookDetail);
        }
       

        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Create()
        {
           
                var bookDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(bookDropdownsData.Categories, "Id", "Name");
               ViewBag.Author = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View();
         
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
                ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            await _services.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _services.GetBookByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                CatId = movieDetails.CatId,
                AuthorId = movieDetails.AuthorId,
            };

            var movieDropdownsData = await _services.GetDropDownValues();

            ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
            ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");

            return View(response);
        }
        [Authorize(Roles = UserRoles.Admin)]

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM book)
        {
            if (id != book.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
                ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");
                return View(book);
            }

            await _services.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

    }
}

BookStore/Controllers/OrdersController.cs
using BookStore.Data.Cart;
using BookStore.Data.Services;
using BookStore.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookStore.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IBookService _bookService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderServices _ordersService;

        public OrdersController(IBookService moviesService, ShoppingCart shoppingCart, IOrderServices ordersService)
        {
            _bookService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            { 

            ShoppingCart = _shoppingCart,
            ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
              };
            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public IActionResult Checkout()
        {
            if (_shoppingCart.GetShoppingCartItems().Count == 0)
            {
                TempData["Error"] = "Your shopping cart is empty. Please add items before checkout.";
                return RedirectToAction(nameof(ShoppingCart));
            }

            var checkoutViewModel = new CheckoutVM();
            return View(checkoutViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutVM checkoutModel)
        {
            if (!ModelState.IsValid)
            {
                return View(checkoutModel);
            }

            return RedirectToAction(nameof(CompleteOrder));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

BookStore/Views/Orders/Checkout.cshtml
@using BookStore.Data.ViewModels;
@model CheckoutVM;

@{
    ViewData["Title"] = "Checkout";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h4 class="text-center mb-4">Checkout</h4>

            <form asp-action="Checkout">

                <div class="form-floating mb-3">
                    <input asp-for="Name" class="form-control" id="Name" placeholder=" " />
                    <label for="Name" class="form-label">Name</label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="Email" class="form-control" id="Email" placeholder=" " />
                    <label for="Email" class="form-label">Email</label>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="PhoneNumber" class="form-control" id="PhoneNumber" placeholder=" " />
                    <label for="PhoneNumber" class="form-label">Phone Number</label>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="Address" class="form-control" id="Address" placeholder=" " />
                    <label for="Address" class="form-label">Address</label>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="Province" class="form-control" id="Province" placeholder=" " />
                    <label for="Province" class="form-label">Province</label>
                    <span asp-validation-for="Province" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="Country" class="form-control" id="Country" placeholder=" " />
                    <label for="Country" class="form-label">Country</label>
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3">
                    <input asp-for="ZipCode" class="form-control" id="ZipCode" placeholder=" " />
                    <label for="ZipCode" class="form-label">Zip Code</label>
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>

                <div class="d-grid gap-2">
                    <button class="btn btn-success" type="submit">Checkout</button>
                    <a class="btn btn-secondary" asp-controller="Orders" asp-action="ShoppingCart">Cancel</a>
                </div>

            </form>
        </div>
    </div>
</div>

BookStore/Views/Orders/Index.cshtml
@model List<Order>

@{ 
    ViewData["Title"] = "All orders";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>List of all your orders</h4>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th> 
                    <th>Items</th>
                    <th>Total</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                <tr>
                    <td class="align-middle">@order.Id</td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.OrderItems)
                            {
                                <li>
                                    <div class="alert alert-info" role="alert">
                                        <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString("c")] - @item.Books.Name
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td class="align-middle">
                        @order.OrderItems.Select(m => m.Books.Price * m.Amount).Sum().ToString("c")
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle"> @order.User.FullName*</td>
                    }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

BookStore/Views/Orders/OrderCompleted.cshtml
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-success">
                <div class="card-body">
                    <h2 class="card-title text-center text-success fw-bold mb-4">Order Completed!</h2>
                    <p class="card-text lead">Your order has been successfully processed.</p>
                    <hr>
                    <p class="card-text">Feel free to view all your orders in your profile's Orders section.</p>
                    <p class="card-text">Thank you for choosing us!</p>
                </div>
            </div>
        </div>
    </div>
</div>

BookStore/Views/Orders/ShoppingCart.cshtml
@using BookStore.Data.ViewModels;
@model ShoppingCartVM


@if (TempData["Error"] != null)
{
    <div class="col-md-12 alert alert-danger">
        <span><b>Sorry!</b> - @TempData["Error"] </span>
    </div>
}
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h2>You shopping cart summary</h2>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Books</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {

                    <tr>
                        <td class="align-middle">@item.Amount</td>
                        <td class="align-middle">@item.Books.Name</td>
                        <td class="align-middle">@item.Books.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Amount * item.Books.Price).ToString("c"))</td>
                        <td class="align-middle">
                            <a class="text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
                               asp-route-id="@item.Books.Id">
                                <i class="bi bi-cart-dash"></i>
                            </a>
                            |
                            <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
                               asp-route-id="@item.Books.Id">
                                <i class="bi bi-cart-plus"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-outline-primary" asp-action="Checkout">
                    Check Out

                </a>
                
                <span style="padding:5px"></span>
                <a class="btn btn-outline-success" asp-controller="Book" asp-action="Index">
                    Add more items
                </a>
            </div>
        </div>

    </div>
</div>