BookStore/Controllers/AuthorController.cs
using BookStore.Data;
using BookStore.Data.Services;
using BookStore.Data.Staic;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class AuthorController : Controller
    {
       

        private readonly IAuthorServices _services;

        public AuthorController(IAuthorServices services)
        {
            _services = services;
        }
    
    public async Task<IActionResult> Index()
        {
            var allAuthors =await _services.GetAllAsync();
            return View(allAuthors);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _services.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Author author)
        {
            if (!ModelState.IsValid) return View(author);

            await _services.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _services.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");
            return View(authorDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,ProfilePictureURL,FullName,Bio")] Author author)
        {

            if (!ModelState.IsValid) return View(author);
            if(id == author.Id)
            {
                await _services.UpdateAsync(id, author);
                return RedirectToAction(nameof(Index));
            }
           
            return View(author);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _services.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorDetails = await _services.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            try
            {
                await _services.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                if (ex.InnerException is SqlException sqlEx && sqlEx.Number == 547)
                {
                    ViewBag.ErrorMessage = "This author cannot be deleted as there are associated books.";
                    return View("Delete", authorDetails);
                }
                throw;
            }
        }



    }
}

BookStore/Controllers/BookController.cs
using BookStore.Data;
using BookStore.Data.Services;
using BookStore.Data.Staic;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Authorize]

    public class BookController : Controller
    {
        private readonly IBookService _services;

        public BookController(IBookService service)
        {
            _services = service;
        }


        public async Task<IActionResult> Index(string searchString)
        {
            var allBooks = await _services.GetAllAsync(n => n.Author, n => n.Category);

            if (!string.IsNullOrEmpty(searchString))
            {
               
                allBooks = allBooks.Where(book => book.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            return View(allBooks);
        }


        public async Task<IActionResult> Details(int id)
        {
            var bookDetail = await _services.GetBookByIdAsync(id);
            return View(bookDetail);
        }
       

        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Create()
        {
           
                var bookDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(bookDropdownsData.Categories, "Id", "Name");
               ViewBag.Author = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View();
         
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
                ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            await _services.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _services.GetBookByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                CatId = movieDetails.CatId,
                AuthorId = movieDetails.AuthorId,
            };

            var movieDropdownsData = await _services.GetDropDownValues();

            ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
            ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");

            return View(response);
        }
        [Authorize(Roles = UserRoles.Admin)]

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM book)
        {
            if (id != book.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _services.GetDropDownValues();

                ViewBag.Category = new SelectList(movieDropdownsData.Categories, "Id", "Name");
                ViewBag.Author = new SelectList(movieDropdownsData.Authors, "Id", "FullName");
                return View(book);
            }

            await _services.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

    }
}

BookStore/Controllers/CategoryController.cs
using BookStore.Data;
using BookStore.Data.Services;
using BookStore.Data.Staic;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoryController : Controller
    {
        private readonly ICategoryServices _services;

        public CategoryController(ICategoryServices services)
        {
            _services = services;
        }

        public async Task<IActionResult> Index()
        {
            var allCategories = await _services.GetAllAsync();
            return View(allCategories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                await _services.AddAsync(category);
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await _services.GetByIdAsync(id);
            if (category == null)
            {
                return View("NotFound");
            }
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _services.UpdateAsync(id, category);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
            }
            return View(category);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var category = await _services.GetByIdAsync(id);
            if (category == null)
            {
                return View("NotFound");
            }
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoryDetails = await _services.GetByIdAsync(id);
            if (categoryDetails == null)
            {
                return View("NotFound");
            }

            try
            {
                await _services.DeleteAsync(id);
                return RedirectToAction("Index"); 
            }
            catch (DbUpdateException ex)
            {
                if (ex.InnerException is SqlException sqlEx && sqlEx.Number == 547)
                {
                    ViewBag.ErrorMessage = "This category cannot be deleted as there are associated Books.";
                    return View("Delete", categoryDetails);
                }
                throw;
            }
        }


    }
}

BookStore/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>
}

BookStore/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;
@if (!User.Identity.IsAuthenticated)
{
    <div class="d-flex">
        <a class="btn btn-outline-success my-2 my-sm-0 me-2" asp-controller="Account" asp-action="Login">
            <i class="bi bi-box-arrow-in-right"></i> Log in
        </a>
        <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
            <i class="bi bi-person-plus"></i> Sign Up
        </a>
    </div>
}
else
{

    <div class="d-flex align-items-center">
        <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="profile-btn" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-badge"></i> @UserManager.GetUserAsync(User).Result.FullName
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile-btn">
                    <li>
                        <a class="dropdown-item" href="/Orders/Index">
                            <i class="bi bi-list"></i> Orders
                        </a>
                        @if (User.IsInRole("Admin"))
                        {
                        <li>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                                <i class="bi bi-people"></i> Users
                            </a>
                        </li>
                        }
            </li>
        </ul>
        </li>
        </ul>

        <form action="@Url.Action("Index", "Book")" method="get" class="d-flex ms-3">
            <input name="searchString" type="text" class="form-control me-2" placeholder="Search for a book..."
                   aria-label="Search" aria-describedby="button-addon2">
            <button class="btn btn-outline-success" type="submit">
                <i class="bi bi-search"></i>
            </button>
        </form>

        <form asp-controller="Account" asp-action="Logout" class="ms-2">
            <button class="btn btn-outline-danger my-2 my-sm-0">
                <i class="bi bi-box-arrow-in-right"></i> Log out
            </button>
        </form>
    </div>
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">
                                <i class="bi bi-book"></i> Books
                            </a>
                        </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Author" asp-action="Index"><i class="bi bi-pen"></i> Author</a></li>
                                    <li><a class="dropdown-item" asp-controller="Category" asp-action="Index"><i class="bi bi-box"></i> Genre</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>